services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      # These variables are now pulled from your .env file
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    networks:
      - gymbuddy-network
    deploy:
      resources:
        limits:
          cpus: '0.1' 
          memory: 512M 

 
networks:
  gymbuddy-network:
    driver: bridge
