services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      # These variables are now pulled from your .env file
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    networks:
      - gymbuddy-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # For SSL certificates
    
    depends_on:
      - app
    networks:
      - gymbuddy-network
networks:
  gymbuddy-network:
    driver: bridge
